services:
  - type: web
    name: shuttle-server
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
